version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      testing:
        patterns:
          - "github.com/stretchr/testify*"
      golang:
        patterns:
          - "golang.org/x/*"
